import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Nav/NavBar';
import { cookies } from 'next/headers';
import ReduxProvider from '@/lib/redux/ReduxProvider';
import TanstackProviders from '@/utils/TanstackProviders';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const modeCookie = (await cookies()).get('mode');
  const isDarkMode = !modeCookie || modeCookie.value !== 'light';
  console.log('모드 : ', modeCookie?.value); //모드 체크용 nextconfig 에서 삭제처리 예정

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${
          isDarkMode ? 'dark' : ''
        } antialiased`}
      >
        <Navbar />
        <ReduxProvider>
          <TanstackProviders>
            <main className="min-h-screen pt-16">{children}</main>
          </TanstackProviders>
        </ReduxProvider>
      </body>
    </html>
  );
}
